title: Elli's world
author: Elli Rhodes
email: pirrikko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm learning to use github. This is my first github pages, and not bad if I do say so myself. 

# social links
twitter_username: s0ftpillow # DO NOT include the @ character, or else the build will fail!
github_username:  ellirhodes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
